# Generated by Django 3.1.4 on 2021-09-06 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210902_0340'),
        ('useraccount', '0003_auto_20210901_0313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField()),
                ('status', models.CharField(choices=[(1, 'Not packed'), (2, 'Packed'), (3, 'Shipped'), (4, 'Delivered')], default=1, max_length=50)),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('razor_pay_order_id', models.CharField(blank=True, max_length=50, null=True)),
                ('razor_pay_payment_id', models.CharField(blank=True, max_length=50, null=True)),
                ('razor_pay_signature', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('price', models.FloatField()),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='useraccount.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.products')),
            ],
        ),
    ]
