# Generated by Django 3.1.4 on 2021-09-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0004_order_orderproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Not packed'), (2, 'Packed'), (3, 'Shipped'), (4, 'Delivered')], default=1, max_length=50),
        ),
    ]
