# Generated by Django 3.2.9 on 2022-10-24 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0006_auto_20220227_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='landmark',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Landmark'),
        ),
        migrations.AlterField(
            model_name='customerotp',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 24, 17, 13, 36, 855631)),
        ),
        migrations.AlterField(
            model_name='customerotp',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 24, 17, 13, 36, 855631)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 24, 17, 13, 36, 855631)),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 24, 17, 13, 36, 855631)),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 24, 17, 13, 36, 855631)),
        ),
    ]
