# Generated by Django 3.2.7 on 2021-09-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0007_auto_20210906_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='razor_pay_signature',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[('Not packed', 'Not packed'), ('Packed', 'Packed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default=1, max_length=50),
        ),
    ]
