# Generated by Django 3.2.7 on 2021-09-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0008_auto_20210911_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Not packed'), (2, 'Packed'), (3, 'Shipped'), (4, 'Delivered')], default=1, max_length=50),
        ),
    ]
