# Generated by Django 3.2.7 on 2021-09-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Not packed'), (2, 'Packed'), (3, 'Shipped'), (4, 'Delivered'), (4, 'Canceled')], default=1, max_length=50),
        ),
    ]
