# Generated by Django 3.2.9 on 2022-01-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0011_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Not packed'), (2, 'Packed'), (3, 'Shipped'), (4, 'Delivered'), (5, 'Canceled')], default=1),
        ),
    ]
