# Generated by Django 3.2.9 on 2022-01-30 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0012_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOtp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('otp', models.IntegerField()),
                ('created', models.DateTimeField(default=datetime.datetime(2022, 1, 30, 15, 22, 26, 655867))),
                ('modified', models.DateTimeField(default=datetime.datetime(2022, 1, 30, 15, 22, 26, 655867))),
            ],
        ),
    ]
