# Generated by Django 3.2.9 on 2022-01-30 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0013_customerotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerotp',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 30, 16, 27, 40, 765380)),
        ),
        migrations.AlterField(
            model_name='customerotp',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 30, 16, 27, 40, 765380)),
        ),
        migrations.AlterField(
            model_name='customerotp',
            name='otp',
            field=models.TextField(),
        ),
    ]
