# Generated by Django 3.2.9 on 2022-01-30 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0015_auto_20220130_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerotp',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 30, 17, 22, 18, 819773)),
        ),
        migrations.AlterField(
            model_name='customerotp',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 30, 17, 22, 18, 819773)),
        ),
        migrations.AlterField(
            model_name='customerotp',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
