# Generated by Django 3.2.9 on 2022-02-06 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0023_auto_20220206_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerotp',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 6, 13, 52, 27, 99987)),
        ),
        migrations.AlterField(
            model_name='customerotp',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 6, 13, 52, 27, 99987)),
        ),
    ]
