# Generated by Django 3.2.9 on 2022-02-12 14:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_products_pr_quantity'),
        ('useraccount', '0028_auto_20220206_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('amount', models.FloatField()),
                ('created', models.DateTimeField(default=datetime.datetime(2022, 2, 12, 20, 8, 3, 363192))),
                ('modified', models.DateTimeField(default=datetime.datetime(2022, 2, 12, 20, 8, 3, 363192))),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='order_status',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[(1, 'Success'), (2, 'Pending'), (3, 'Failed')], default=2, max_length=10),
        ),
        migrations.AlterField(
            model_name='customerotp',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 12, 20, 8, 3, 363192)),
        ),
        migrations.AlterField(
            model_name='customerotp',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 12, 20, 8, 3, 363192)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 12, 20, 8, 3, 363192)),
        ),
        migrations.DeleteModel(
            name='OrderProducts',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='useraccount.order'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.products'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='product_variation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productvariation'),
        ),
    ]
