# Generated by Django 3.1.4 on 2021-09-01 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_name', models.CharField(max_length=200, verbose_name='product name')),
                ('pr_price', models.FloatField(verbose_name='product price')),
                ('pr_quantity', models.IntegerField(verbose_name='product quantity')),
                ('pr_image', models.ImageField(upload_to='images/', verbose_name='product image')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('pr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
        ),
    ]
