# Generated by Django 3.1.4 on 2021-09-02 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210902_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='pr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.products'),
        ),
    ]
