# Generated by Django 3.2.7 on 2021-09-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210915_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='pr_brand',
            field=models.CharField(choices=[('Apple', 'Apple'), ('Samsung', 'Samsung'), ('Redmi', 'Redmi'), ('Realme', 'Realme'), ('Oppo', 'Oppo'), ('Vivo', 'Vivo'), ('Moto', 'Moto'), ('Oneplus', 'Oneplus')], default='Apple', max_length=200, verbose_name='Brand'),
        ),
    ]
