# Generated by Django 3.2.7 on 2021-09-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_products_pr_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='processor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
