# Generated by Django 3.2.7 on 2021-09-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productdetails_processor'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='camera',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
