# Generated by Django 3.2.9 on 2022-01-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productdetails_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='out_of_stock',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
