# Generated by Django 3.2.9 on 2022-01-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20220130_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='out_of_stock',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
