# Generated by Django 3.2.9 on 2022-02-06 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_products_out_of_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Brand Name')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Category Name')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Color')),
            ],
        ),
        migrations.RemoveField(
            model_name='products',
            name='pr_brand',
        ),
        migrations.AddField(
            model_name='products',
            name='pr_description',
            field=models.CharField(max_length=200, null=True, verbose_name='Product Description'),
        ),
        migrations.DeleteModel(
            name='ProductDetails',
        ),
        migrations.AddField(
            model_name='products',
            name='pr_brand_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.brand', verbose_name='Brand Id'),
        ),
        migrations.AddField(
            model_name='products',
            name='pr_category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Category Id'),
        ),
        migrations.AddField(
            model_name='products',
            name='pr_color_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.color'),
        ),
    ]
