# Generated by Django 3.2.9 on 2022-02-06 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20220206_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='pr_brand_id',
            new_name='pr_brand',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='pr_category_id',
            new_name='pr_category',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='pr_color_id',
            new_name='pr_color',
        ),
    ]
