# Generated by Django 3.2.9 on 2022-02-06 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20220206_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='pr_color',
        ),
        migrations.RemoveField(
            model_name='products',
            name='pr_description',
        ),
        migrations.RemoveField(
            model_name='products',
            name='pr_image',
        ),
        migrations.RemoveField(
            model_name='products',
            name='pr_price',
        ),
        migrations.AlterField(
            model_name='products',
            name='pr_name',
            field=models.CharField(max_length=200, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='products',
            name='pr_quantity',
            field=models.IntegerField(verbose_name='Product Quantity'),
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Product Image')),
                ('price', models.FloatField(verbose_name='Product Price')),
                ('quantity', models.IntegerField(verbose_name='Product Quantity')),
                ('active', models.BooleanField(default=True, null=True)),
                ('out_of_stock', models.BooleanField(default=False, null=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products', verbose_name='Product Id')),
            ],
        ),
    ]
