# Generated by Django 3.2.9 on 2022-02-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20220206_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='pr_quantity',
            field=models.IntegerField(null=True, verbose_name='Product Quantity'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
    ]
